MyCmsNewsProject/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace MyCmsNewsProject.Controllers
{
    public class NewsController : Controller
    {
        MyCmsContext db = new MyCmsContext();
        private IPageGroupRepository pageGroupRepository;
        private IPageRepository pageRepository;
        private IPageCommentRepository pageCommentRepository;
        public NewsController()
        {
            pageGroupRepository = new PageGroupRepository(db);
            pageRepository = new PageRepository(db);
            pageCommentRepository = new PageCommentRepository(db);
        }
        // GET: News
        public ActionResult ShowGroups()
        {
            return PartialView(pageGroupRepository.GetGroupForView());
        }
        public ActionResult ShowGroupsInMenu()
        {
            return PartialView(pageGroupRepository.GetAllGroups());
        }

        public ActionResult TopNews()
        {
            return PartialView(pageRepository.TopNews());
        }
        public ActionResult LatesNews()
        {
            return PartialView(pageRepository.LastNews());
        }
        [Route("Archive")]
        public ActionResult ArchiveNews()
        {
            return View(pageRepository.GetAllPage());
        }
        [Route("Group/{id}/{title}")]
        public ActionResult ShowNewsByGroupId(int id,string title)
        {
            ViewBag.name = title;
            return View(pageRepository.ShowPageByGroupId(id));

        }
        [Route("News/{id}")]
        public ActionResult ShowNews(int id )
        {
            var news = pageRepository.GetPageById(id);
            if (news==null)
            {
                return HttpNotFound();
            }
            news.Visit += 1;
            pageRepository.UpdatePage(news);
            pageRepository.Save();
            return View(news);
        }
        public ActionResult AddComment(int id, string name, string email, string comment)
        {
            PageComment addcomment = new PageComment()
            {
                CreateDate = DateTime.Now,
                PageID = id,
                Comment = comment,
                Email = email,
                Name = name
            };
            pageCommentRepository.AddComment(addcomment);

            return PartialView("ShowComments", pageCommentRepository.GetCommentByNewsId(id));
        }

        public ActionResult ShowComments(int id)
        {
            return PartialView(pageCommentRepository.GetCommentByNewsId(id));
        }
    }
}

MyCmsNewsProject/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>سایت خبری </title>
    <base href="">
    <meta name="googlebot" content="index,follow">
    <meta name="robots" content="noodp,noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css">
    <script src="/Content/js/jquery.min.js"></script>
</head>
<body>
    <script src="/Content/js/modernizr.js"></script>

    <!-- Top Menu -->
    <div class="top-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-5">
                    <ul>
                        <li><a href=""><i class="fa fa-home"></i></a></li>
                        <li><a href=""><i class="fa fa-question-circle"></i></a></li>
                        <li><a href=""><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-7">
                    <span>امروز : @DateTime.Now</span>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Menu -->
    <!-- header -->
    <header class="main-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a href="" class="logo"><img src="img/logo.png" alt="" title=""></a>
                    <div class="left-side">
                        <h1><a href="">سایت خبری </a></h1>
                        <h2> پایگاه اطلاع رسانی و خبری</h2>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <form action="/Search" method="get" class="border-radius">
                        <input class="border-radius" type="text"name="q"  placeholder=" جستجو کنید ... ">
                        <button><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- End Header -->
    <!-- menu -->
    <nav class="main-menu">
        <div class="container">
            <span><i class="fa fa-th-list"></i></span>
            <ul>
                <li><a href="/"> صفحه اصلی </a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a href="">@User.Identity.Name خوش آمدید </a></li>
                    <li><a href="/Account/SignOut">خروج </a></li>
                }
                else
                {
                    <li><a href="/Account/Login">ورود به سایت </a></li>
                }
                <li>
                    @Html.Action("ShowGroupsInMenu", "News")
                </li>
            </ul>
        </div>
    </nav>
    <!-- End menu -->
   
    <div class="container margin-top-30">
        <div class="row">
           
            <div class="col-md-8 col-sm-12 col-xs-12 pull-left">

                @RenderBody()

            </div>


            <aside class="col-md-4 col-sm-12 col-xs-12 pull-right">

                @if (User.Identity.IsAuthenticated)
                {
                <div class="thumbnail">
                    <ul>
                        <li>
                            <a href="/Admin/PageGroups">مدیریت گروه ها</a>
                        </li>
                        <li>
                            <a href="/Admin/Pages">مدیریت صفحات</a>
                        </li>

                    </ul>
                </div>
                }
                @Html.Action("ShowGroups", "News")

                <!-- most views news -->
                @Html.Action("TopNews", "News")
                <!-- end most views news -->
            </aside>

        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <section class="access-links">
                        <header> دسترسی سریع </header>
                        <ul>
                            <li><a href="/"> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> راهنمای سایت  </a></li>
                            <li><a href=""> پیوندهای سایت </a></li>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> راهنمای سایت  </a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
                    <div class="socials">
                        <span> شبکه های اجتماعی  سایت</span>
                        <a href=""><i class="fa fa-facebook"></i></a>
                        <a href=""><i class="fa fa-twitter"></i></a>
                        <a href=""><i class="fa fa-paper-plane"></i></a>
                        <a href=""><i class="fa fa-google-plus"></i></a>
                        <div class="clearfix"></div>
                    </div>
                    <p>
                        تمامی حقوق مادی و معنوی این طرح متعلق به آموزشگاه برنامه نویسان می باشد و کپی برداری از این طرح غیر اخلاقی می باشد.
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/owl.carousel.js"></script>
    <script src="~/Content/js/script.js"></script>
    @RenderSection("Scripts",false)
</body>
</html>

MyCmsNewsProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>